### ISSUE TITLE
On Main Menu buttons for changeScene doesn't work

### ISSUE THREAD

**Issue by andreamancuso098** [LucaFalasca/Hunts#95]
Appena clicco un bottone per cambiare scena non funziona 
"Caused by: java.lang.NullPointerException: Cannot invoke "javafx.stage.Stage.getScene()" because "this.stage" is null"

**Comment by LucaFalasca** [comment]
Postami l'errore completo perchè siccome a me non succede riesco a capire meglio @andreamancuso098

**Comment by andreamancuso098** [comment]
Nel momento in cui logghi puoi visualizzare le mappe presenti. Se clicchi il tasto cancella nella ListView delle mappe funziona. Invece se clicchi il tasto modifica da questo errore:
Caused by: java.lang.NullPointerException: Cannot invoke "javafx.stage.Stage.getScene()" because "this.stage" is null
	at logic.view.desktop.controller.ControllerWithLogin.changeScene(ControllerWithLogin.java:99)
	at logic.view.desktop.controller.ControllerWithLogin.changeScene(ControllerWithLogin.java:95)
	at logic.view.desktop.controller.ItemMapGController.handleModifyMap(ItemMapGController.java:57)
	... 69 more

**Comment by LucaFalasca** [comment]
Non posso risolvere l'errore perchè è su ItemMapGController, ed è una classe che io non ho. Quindi devi fare un commit prima
@andreamancuso098
